#!/bin/bash

if [ "$#" -le 0 ]; then
    echo "Wrong Argument."
    echo "Show Help: showtmuxpane -h"
    exit 1
elif [ "$#" -eq 1 ]; then
    if [ "$@" = "-h" ] || [ "$@" = "--help" ]; then
        echo "Argument"
        echo "-h, --help: show help"
        echo ""
        echo "-t: <window number>"
        echo "-S: <start line>"
        echo ""
        echo "The -E option is set as the default value, and this cannot be changed."
        echo "    Default Value: \$((\$(tmux display -p -t <window_number> '#{pane_height}') - 2))"
        echo "The p option is enabled, and this cannot be changed."
        exit 0
    fi
fi
display_window="$1"
shift
windowlist="$(tmux list-windows | grep -P '^[0-9]+:' | awk -F ':' '{print $1}')"
is_exist=$(echo "$windowlist" | grep "^$display_window$")
if [ -z "$is_exist" ]; then
	echo "window number is wrong"
	exit 1
fi
tmux capture-pane -t $display_window -p -E $(($(tmux display -p -t $display_window '#{pane_height}') - 2)) $@ 
# tmux capture-pane -t 2 -p -S -30 -E $(($(tmux display -p -t 2 '#{pane_height}') - 2))

