# github : https://github.com/bensadeh/tailspin

[[regexps]]
regular_expression = '^([0-9]{2}\/[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})'
style = { fg = "cyan" }



[[regexps]]
regular_expression = '(\| ERR:[a-zA-Z0-9_]*:)'
style = { fg = "red" }

[[regexps]]
regular_expression = '(\| INF:[a-zA-Z0-9_]*:)'
style = { fg = "yellow" }

[[regexps]]
regular_expression = '(\| [a-zA-Z0-9_]*:)'
style = { fg = "green" }



[[regexps]]
regular_expression = '(syn [0-9]* fin [0-9-]* ack [0-9-]* rst [0-9-]* urg [0-9-]*)'
style = { fg = "magenta" }



[[regexps]]
regular_expression = '( FD -[0-9]*)'
style = { fg = "magenta" }

[[regexps]]
regular_expression = '( FD [0-9]*[13579]{1})'
style = { fg = "cyan", italic = true }

[[regexps]]
regular_expression = '( FD [0-9]*[02468]{1})'
style = { fg = "blue", italic = true }



[[regexps]]
regular_expression = '(  src [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}, dest [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$)'
style = { fg = "magenta" }

[[regexps]]
regular_expression = '( src [0-9]{1,5}, dst [0-9]{1,5}$)'
style = { fg = "magenta" }



[[regexps]]
regular_expression = '( incomming seq -?[0-9]*, ack -?[0-9]*, wnd -?[0-9]*$)'
style = { fg = "cyan" }

[[regexps]]
regular_expression = '( outgoing seq -?[0-9]*, ack -?[0-9]*, wnd -?[0-9]*$)'
style = { fg = "blue" }








# default

[date]
disabled = true
number = { fg = "magenta" }
separator = { faint = true }

[date_word] # e.g. "Jan 01", "Mon Feb 28"
disabled = true
day = { fg = "magenta" }
month = { fg = "magenta" }
number = { fg = "magenta" }

[[keywords]]
disabled = true
words = ['null', 'true', 'false']
# style = { fg = "red", italic = true }
style = { fg = "", italic = false }

[[keywords]]
disabled = true
words = ['GET']
# style = { fg = "black", bg = "green" }
style = { fg = "", italic = false }

border = true
[time]
disabled = true
time = { fg = "blue" }
zone = { fg = "red" }
separator = { faint = true }

[[keywords]]
disabled = true
words = ['null', 'true', 'false']
style = { fg = "red", italic = true }

[[keywords]]
disabled = true
words = ['GET']
style = { fg = "black", bg = "green" }
border = true

[url]
disabled = true
http = { fg = "red", faint = true }
https = { fg = "green", faint = true }
host = { fg = "blue", faint = true }
path = { fg = "blue" }
query_params_key = { fg = "magenta" }
query_params_value = { fg = "cyan" }
symbols = { fg = "red" }

[number]
disabled = true
style = { fg = "cyan" }

[ip]
disabled = true
number = { fg = "blue", italic = true }
letter = { fg = "magenta", italic = true }
separator = { fg = "red" }

[quotes]
disabled = true
style = { fg = "yellow" }
token = '"'

[path]
disabled = true
segment = { fg = "green", italic = true }
separator = { fg = "yellow" }

[uuid]
disabled = true
number = { fg = "blue", italic = true }
letter = { fg = "magenta", italic = true }
separator = { fg = "red" }

[pointer]
disabled = true
number = { fg = "blue", italic = true }
letter = { fg = "magenta", italic = true }
separator = { fg = "red" }

[key_value]
disabled = true
key = { faint = true }
separator = { fg = "white" }

[process]
disabled = true
name = { fg = "green" }
separator = { fg = "red" }
id = { fg = "yellow" }




