#!/bin/bash

if [ "$#" -eq 0 ] || [ "$1" = "s" ]; then
    claude --model=opus --append-system-prompt "$(cat $HOME/.dotfiles/prompt/global_prompt.md)"
elif [ "$1" = "u" ] || [ "$1" = "su" ]; then
    claude --model=opus --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests$(echo )$(cat $HOME/.dotfiles/prompt/global_prompt.md)"
elif [ "$1" = "a" ]; then
    claude --model=sonnet --append-system-prompt "$(cat $HOME/.dotfiles/prompt/global_prompt.md)"
elif [ "$1" = "au" ]; then
    claude --model=sonnet --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests$(echo )$(cat $HOME/.dotfiles/prompt/global_prompt.md)"
else
    claude --model=opus --append-system-prompt "$(cat $HOME/.dotfiles/prompt/global_prompt.md)"
fi

