#!/bin/bash


CLAUDE_OPT=""

if [ $# -eq 0 ]; then
    CLAUDE_OPT="s"
else
    if [ "$1" == "s" ] || [ "$1" == "u" ] ||  [ "$1" == "su" ] || [ "$1" == "a" ] || [ "$1" == "au" ] || [ "$1" == "h" ] || [ "$1" == "hu" ]; then
        CLAUDE_OPT="$1"
        shift
    else
        # CLAUDE_OPT="s"
		echo -n ""
    fi
fi

CLAUDE_OPT=$(echo $CLAUDE_OPT | sed 's/.*/\L&/')

for opt in "$@"; do
    if [ "$opt" = "--dan" ]; then
        BYPASS_OPT="--dangerously-skip-permissions"
        set -- "${@/--dan/}"
        break
    elif [ "$opt" = "-d" ]; then
        BYPASS_OPT="--dangerously-skip-permissions"
        set -- "${@/-d/}"
        break
    fi
done

# if ( grep -q -- "--dan" <<< "$*" ); then
#     BYPASS_OPT="--dangerously-skip-permissions"
#     shift
# fi


PROMPT_PATH="$HOME/.dotfiles/prompt/global_prompt.md"

if [ "$CLAUDE_OPT" = "s" ]; then
    claude --model=opus $BYPASS_OPT --append-system-prompt "$(cat $PROMPT_PATH)" $@
elif [ "$CLAUDE_OPT" = "u" ] || [ "$CLAUDE_OPT" = "su" ]; then
    claude --model=opus $BYPASS_OPT --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests$(echo )$(cat $PROMPT_PATH)" $@
elif [ "$CLAUDE_OPT" = "a" ]; then
    claude --model=sonnet $BYPASS_OPT --append-system-prompt "$(cat $PROMPT_PATH)" $@
elif [ "$CLAUDE_OPT" = "au" ]; then
    claude --model=sonnet $BYPASS_OPT --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests$(echo )$(cat $PROMPT_PATH) $@"
elif [ "$CLAUDE_OPT" = "h" ]; then
    claude --model=haiku $BYPASS_OPT --append-system-prompt "$(cat $PROMPT_PATH)" $@
elif [ "$CLAUDE_OPT" = "hu" ]; then
    claude --model=haiku $BYPASS_OPT --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests$(echo )$(cat $PROMPT_PATH) $@"
else
    claude --model=opus $BYPASS_OPT --append-system-prompt "$(cat $PROMPT_PATH)" $@
fi

