#!/bin/bash


CLAUDE_OPT="a"

if [ $# -eq 0 ]; then
    CLAUDE_OPT="a"
else
    if [ "$1" == "s" ] || [ "$1" == "u" ] ||  [ "$1" == "su" ] || [ "$1" == "a" ] || [ "$1" == "au" ] || [ "$1" == "h" ] || [ "$1" == "hu" ]; then
        CLAUDE_OPT="$1"
        shift
    else
        # CLAUDE_OPT="s"
        echo -n ""
    fi
fi

CLAUDE_OPT=$(echo $CLAUDE_OPT | sed 's/.*/\L&/')

for opt in "$@"; do
    if [ "$opt" = "--dan" ]; then
        BYPASS_OPT="--dangerously-skip-permissions"
        set -- "${@/--dan/}"
        break
    elif [ "$opt" = "-d" ]; then
        BYPASS_OPT="--dangerously-skip-permissions"
        set -- "${@/-d/}"
        break
    fi
done

# if ( grep -q -- "--dan" <<< "$*" ); then
#     BYPASS_OPT="--dangerously-skip-permissions"
#     shift
# fi


# PROMPT_PATH="$HOME/.dotfiles/prompt/global_prompt.md"
# ~/.claude/CLAUDE.md -> @global_prompt.md
# ln -s $HOME/.dotfiles/prompt/global_prompt.md $HOME/.claude/
# if [ -n "$(grep '^@global_prompt.md$' CLAUDE.md)" ]; then
#     echo -e "hello world!\n$(cat $HOME/.claude/CLAUDE.md)" > $HOME/.claude/CLAUDE.md
#     echo -e "@global_prompt.md\n\n$(cat $HOME/.claude/CLAUDE.md)" > $HOME/.claude/CLAUDE.md
# fi
PROMPT_PATH=""

if [ "$CLAUDE_OPT" = "s" ]; then
    if [ -f "$PROMPT_PATH" ] ;then
        claude --model=opus $BYPASS_OPT --append-system-prompt "$(cat $PROMPT_PATH)" $@
    else
        claude --model=opus $BYPASS_OPT $@
    fi
elif [ "$CLAUDE_OPT" = "u" ] || [ "$CLAUDE_OPT" = "su" ]; then
    if [ -f "$PROMPT_PATH" ] ;then
        claude --model=opus $BYPASS_OPT --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests$(echo )$(cat $PROMPT_PATH)" $@
    else
        claude --model=opus $BYPASS_OPT --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests" $@
    fi
elif [ "$CLAUDE_OPT" = "a" ]; then
    if [ -f "$PROMPT_PATH" ] ;then
        claude --model=sonnet $BYPASS_OPT --append-system-prompt "$(cat $PROMPT_PATH)" $@
    else
        claude --model=sonnet $BYPASS_OPT $@
    fi
elif [ "$CLAUDE_OPT" = "au" ]; then
    if [ -f "$PROMPT_PATH" ] ;then
        claude --model=sonnet $BYPASS_OPT --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests$(echo )$(cat $PROMPT_PATH)" $@
    else
        claude --model=sonnet $BYPASS_OPT --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests" $@
    fi
elif [ "$CLAUDE_OPT" = "h" ]; then
    if [ -f "$PROMPT_PATH" ] ;then
        claude --model=haiku $BYPASS_OPT --append-system-prompt "$(cat $PROMPT_PATH)" $@
    else
        claude --model=haiku $BYPASS_OPT $@
    fi
elif [ "$CLAUDE_OPT" = "hu" ]; then
    if [ -f "$PROMPT_PATH" ] ;then
        claude --model=haiku $BYPASS_OPT --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests$(echo )$(cat $PROMPT_PATH)" $@
    else
        claude --model=haiku $BYPASS_OPT --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests" $@
    fi
else
    if [ -f "$PROMPT_PATH" ] ;then
        claude --model=sonnet $BYPASS_OPT --append-system-prompt "$(cat $PROMPT_PATH)" $@
    else
        claude --model=sonnet $BYPASS_OPT $@
    fi
fi

