#!/bin/bash

VIM_PROGRAM=""
CLAUDE_OPT="s"

NVIM_PATH="nvim"
VIM_PATH="vim"

if [ -n $(which $NVIM_PATH) ]; then
    VIM_PROGRAM="n"
else
    VIM_PROGRAM="o"
fi

# VIM_DEFAULT=$(vim --version | head -n 1 | awk '{ print $1 }')
# if [ "$VIM_DEFAULT" = "NVIM" ]; then
#     VIM_PROGRAM="n"
# else
#     VIM_PROGRAM="o"
# fi


# VIM_PROGRAM -> n: neovim, o: original vim
# CLAUDE -> s: opus, a: sonnet

if [ $# -eq 0 ]; then
    CLAUDE_OPT="s"
elif [ $# -eq 1 ]; then
    if [ "$1" = "n" ] || [ "$1" = "N" ]; then
        VIM_PROGRAM="n"
        CLAUDE_OPT="s"
    elif [ "$1" = "o" ] || [ "$1" = "O" ]; then
        VIM_PROGRAM="o"
    else
        CLAUDE_OPT="$1"
    fi
else
    VIM_PROGRAM="$1"
    CLAUDE_OPT="$2"
fi

if [ "$VIM_PROGRAM" = "n" ]; then
    if [ "$CLAUDE_OPT" = "s" ]; then
        $NVIM_PATH -c "set nonu | set nornu | set mouse=a | set scrollback=10000 | tnoremap <C-i> \\<CR>" \
            -c "terminal bash -c '$HOME/.dotfiles/.bin/clds; exit_code=\$?; exit \$exit_code'" \
            -c "autocmd TermClose * if v:event.status == 0 | quit | endif" \
            -c "startinsert"
    elif [ "$CLAUDE_OPT" = "u" ] || [ "$CLAUDE_OPT" = "su" ]; then
        $NVIM_PATH -c "set nonu | set nornu | set mouse=a | set scrollback=10000 | tnoremap <C-i> \\<CR>" \
            -c "terminal bash -c '$HOME/.dotfiles/.bin/cldsu; exit_code=\$?; exit \$exit_code'" \
            -c "autocmd TermClose * if v:event.status == 0 | quit | endif" \
            -c "startinsert"
    elif [ "$CLAUDE_OPT" = "a" ]; then
        $NVIM_PATH -c "set nonu | set nornu | set mouse=a | set scrollback=10000 | tnoremap <C-i> \\<CR>" \
            -c "terminal bash -c '$HOME/.dotfiles/.bin/clda; exit_code=\$?; exit \$exit_code'" \
            -c "autocmd TermClose * if v:event.status == 0 | quit | endif" \
            -c "startinsert"
    elif [ "$CLAUDE_OPT" = "au" ]; then
        $NVIM_PATH -c "set nonu | set nornu | set mouse=a | set scrollback=10000 | tnoremap <C-i> \\<CR>" \
            -c "terminal bash -c '$HOME/.dotfiles/.bin/cldau; exit_code=\$?; exit \$exit_code'" \
            -c "autocmd TermClose * if v:event.status == 0 | quit | endif" \
            -c "startinsert"
    else
        $NVIM_PATH -c "set nonu | set nornu | set mouse=a | set scrollback=10000 | tnoremap <C-i> \\<CR>" \
            -c "terminal bash -c '$HOME/.dotfiles/.bin/clds; exit_code=\$?; exit \$exit_code'" \
            -c "autocmd TermClose * if v:event.status == 0 | quit | endif" \
            -c "startinsert"
    fi
else
	if [ "$CLAUDE_OPT" = "s" ]; then
        $VIM_PATH -c "set nonu | set nornu | set mouse=a | set termwinscroll=10000 | tnoremap <C-i> \\<CR>" \
            -c "terminal ++close ++curwin bash -c '$HOME/.dotfiles/.bin/clds'"
            # -c "call term_start('bash -c \"$HOME/.dotfiles/.bin/clds\"', {'curwin': 1, 'term_finish': 'close', 'exit_cb': {job, status -> execute('quit!')}})"
    elif [ "$CLAUDE_OPT" = "u" ] || [ "$CLAUDE_OPT" = "su" ]; then
        $VIM_PATH -c "set nonu | set nornu | set mouse=a | set termwinscroll=10000 | tnoremap <C-i> \\<CR>" \
            -c "call term_start('bash -c \"$HOME/.dotfiles/.bin/cldsu\"', {'curwin': 1, 'term_finish': 'close', 'exit_cb': {job, status -> execute('quit!')}})"
    elif [ "$CLAUDE_OPT" = "a" ]; then
        $VIM_PATH -c "set nonu | set nornu | set mouse=a | set termwinscroll=10000 | tnoremap <C-i> \\<CR>" \
            -c "call term_start('bash -c \"$HOME/.dotfiles/.bin/clda\"', {'curwin': 1, 'term_finish': 'close', 'exit_cb': {job, status -> execute('quit!')}})"
    elif [ "$CLAUDE_OPT" = "au" ]; then
        $VIM_PATH -c "set nonu | set nornu | set mouse=a | set termwinscroll=10000 | tnoremap <C-i> \\<CR>" \
            -c "call term_start('bash -c \"$HOME/.dotfiles/.bin/cldau\"', {'curwin': 1, 'term_finish': 'close', 'exit_cb': {job, status -> execute('quit!')}})"
    else
        $VIM_PATH -c "set nonu | set nornu | set mouse=a | set termwinscroll=10000 | tnoremap <C-i> \\<CR>" \
            -c "call term_start('bash -c \"$HOME/.dotfiles/.bin/clds\"', {'curwin': 1, 'term_finish': 'close', 'exit_cb': {job, status -> execute('quit!')}})"
    fi
fi

exit 0