#!/bin/bash

VIM_PROGRAM=""
CLAUDE_OPT="s"

NVIM_PATH="nvim"
VIM_PATH="vim"

if [ -n $(command -v $NVIM_PATH) ]; then
    VIM_PROGRAM="n"
else
    VIM_PROGRAM="o"
fi

# VIM_DEFAULT=$(vim --version | head -n 1 | awk '{ print $1 }')
# if [ "$VIM_DEFAULT" = "NVIM" ]; then
#     VIM_PROGRAM="n"
# else
#     VIM_PROGRAM="o"
# fi


# VIM_PROGRAM -> n: neovim, o: original vim
# CLAUDE -> s: opus, a: sonnet

if [ $# -eq 0 ]; then
    CLAUDE_OPT="s"
elif [ $# -eq 1 ]; then
    if [ "$1" = "n" ] || [ "$1" = "N" ]; then
        VIM_PROGRAM="n"
        CLAUDE_OPT="s"
    elif [ "$1" = "o" ] || [ "$1" = "O" ]; then
        VIM_PROGRAM="o"
    else
        CLAUDE_OPT="$1"
    fi
else
    VIM_PROGRAM="$1"
    CLAUDE_OPT="$2"
fi

if [ -n "$VIMTERM" ] && [ "$VIMTERM" -eq "1" ]; then
    if [ "$CLAUDE_OPT" = "s" ]; then
        $HOME/.dotfiles/.bin/cld "s"
    elif [ "$CLAUDE_OPT" = "u" ] || [ "$CLAUDE_OPT" = "su" ]; then
        $HOME/.dotfiles/.bin/cld "su"
    elif [ "$CLAUDE_OPT" = "a" ]; then
        $HOME/.dotfiles/.bin/cld "a"
    elif [ "$CLAUDE_OPT" = "au" ]; then
        $HOME/.dotfiles/.bin/cld "au"
    fi
    exit 0
fi

if [ "$VIM_PROGRAM" = "n" ]; then
    if [ "$CLAUDE_OPT" = "s" ]; then
		echo "opus"
        $NVIM_PATH -c "set nonu | set nornu | set mouse=a | set scrollback=10000 | set scrolloff=0 | tnoremap <C-i> \\<CR>" \
            -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
            -c "terminal bash -c '$HOME/.dotfiles/.bin/cld; exit_code=\$?; exit \$exit_code'" \
            -c "autocmd TermClose * if v:event.status == 0 | quit | endif" \
            -c "startinsert"
    elif [ "$CLAUDE_OPT" = "u" ] || [ "$CLAUDE_OPT" = "su" ]; then
        $NVIM_PATH -c "set nonu | set nornu | set mouse=a | set scrollback=10000 | set scrolloff=0 | tnoremap <C-i> \\<CR>" \
            -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
            -c "terminal bash -c '$HOME/.dotfiles/.bin/cld su; exit_code=\$?; exit \$exit_code'" \
            -c "autocmd TermClose * if v:event.status == 0 | quit | endif" \
            -c "startinsert"
    elif [ "$CLAUDE_OPT" = "a" ]; then
        $NVIM_PATH -c "set nonu | set nornu | set mouse=a | set scrollback=10000 | set scrolloff=0 | tnoremap <C-i> \\<CR>" \
            -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
            -c "terminal bash -c '$HOME/.dotfiles/.bin/cld a; exit_code=\$?; exit \$exit_code'" \
            -c "autocmd TermClose * if v:event.status == 0 | quit | endif" \
            -c "startinsert"
    elif [ "$CLAUDE_OPT" = "au" ]; then
        $NVIM_PATH -c "set nonu | set nornu | set mouse=a | set scrollback=10000 | set scrolloff=0 | tnoremap <C-i> \\<CR>" \
            -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
            -c "terminal bash -c '$HOME/.dotfiles/.bin/cld au; exit_code=\$?; exit \$exit_code'" \
            -c "autocmd TermClose * if v:event.status == 0 | quit | endif" \
            -c "startinsert"
    else
        $NVIM_PATH -c "set nonu | set nornu | set mouse=a | set scrollback=10000 | set scrolloff=0 | tnoremap <C-i> \\<CR>" \
            -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
            -c "terminal bash -c '$HOME/.dotfiles/.bin/cld; exit_code=\$?; exit \$exit_code'" \
            -c "autocmd TermClose * if v:event.status == 0 | quit | endif" \
            -c "startinsert"
    fi
else
    if [ "$CLAUDE_OPT" = "s" ]; then
        $VIM_PATH -c "set nonu | set nornu | set mouse=a | set termwinscroll=10000 | set scrolloff=0 | tnoremap <C-i> \\<CR>" \
            -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
            -c "set shell=$(which zsh | sed 's/ /\\ /g')" \
            -c "terminal ++close ++curwin bash -c '$HOME/.dotfiles/.bin/cld'"
            # -c "call term_start('bash -c \"$HOME/.dotfiles/.bin/cld\"', {'curwin': 1, 'term_finish': 'close', 'exit_cb': {job, status -> execute('quit!')}})"
    elif [ "$CLAUDE_OPT" = "u" ] || [ "$CLAUDE_OPT" = "su" ]; then
        $VIM_PATH -c "set nonu | set nornu | set mouse=a | set termwinscroll=10000 | set scrolloff=0 | tnoremap <C-i> \\<CR>" \
            -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
            -c "set shell=$(which zsh | sed 's/ /\\ /g')" \
            -c "call term_start('bash -c \"$HOME/.dotfiles/.bin/cld su\"', {'curwin': 1, 'term_finish': 'close', 'exit_cb': {job, status -> execute('quit!')}})"
    elif [ "$CLAUDE_OPT" = "a" ]; then
        $VIM_PATH -c "set nonu | set nornu | set mouse=a | set termwinscroll=10000 | set scrolloff=0 | tnoremap <C-i> \\<CR>" \
            -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
            -c "set shell=$(which zsh | sed 's/ /\\ /g')" \
            -c "call term_start('bash -c \"$HOME/.dotfiles/.bin/cld a\"', {'curwin': 1, 'term_finish': 'close', 'exit_cb': {job, status -> execute('quit!')}})"
    elif [ "$CLAUDE_OPT" = "au" ]; then
        $VIM_PATH -c "set nonu | set nornu | set mouse=a | set termwinscroll=10000 | set scrolloff=0 | tnoremap <C-i> \\<CR>" \
            -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
            -c "set shell=$(which zsh | sed 's/ /\\ /g')" \
            -c "call term_start('bash -c \"$HOME/.dotfiles/.bin/cld au\"', {'curwin': 1, 'term_finish': 'close', 'exit_cb': {job, status -> execute('quit!')}})"
    else
        $VIM_PATH -c "set nonu | set nornu | set mouse=a | set termwinscroll=10000 | set scrolloff=0 | tnoremap <C-i> \\<CR>" \
            -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
            -c "set shell=$(which zsh | sed 's/ /\\ /g')" \
            -c "call term_start('bash -c \"$HOME/.dotfiles/.bin/cld\"', {'curwin': 1, 'term_finish': 'close', 'exit_cb': {job, status -> execute('quit!')}})"
    fi
fi

exit 0
