#!/bin/bash


CLAUDE_OPT=""

if [ $# -eq 0 ]; then
    CLAUDE_OPT="a"
else
    if [ "$1" == "s" ] || [ "$1" == "u" ] ||  [ "$1" == "su" ] || [ "$1" == "a" ] || [ "$1" == "au" ]; then
        CLAUDE_OPT="$1"
        shift
    else
        CLAUDE_OPT="a"
    fi
fi


PROMPT_PATH="$HOME/.dotfiles/prompt/translate_file_prompt.md"

if [ "$CLAUDE_OPT" = "s" ]; then
    claude --model=opus --append-system-prompt "$(cat $PROMPT_PATH)" $@
elif [ "$CLAUDE_OPT" = "u" ] || [ "$CLAUDE_OPT" = "su" ]; then
    claude --model=opus --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests$(echo )$(cat $PROMPT_PATH)" $@
elif [ "$CLAUDE_OPT" = "a" ]; then
    claude --model=sonnet --append-system-prompt "$(cat $PROMPT_PATH)" $@
elif [ "$CLAUDE_OPT" = "au" ]; then
    claude --model=sonnet --append-system-prompt "/sc:implement --ultrathink --seq --c7 --play --iterative --with-tests$(echo )$(cat $PROMPT_PATH) $@"
else
    claude --model=opus --append-system-prompt "$(cat $PROMPT_PATH)" $@
fi

