#!/bin/bash

# echo "VIM_PROG: $VIM_PROGRAM"
if [ -z "$VIM_PROGRAM" ]; then
    if [ -z "$(command -v nvim)" ]; then
        VIM_PROGRAM="nvim"
    else
        VIM_PROGRAM="vim"
    fi
else
    validate_var=$(command -v "$VIM_PROGRAM")
    if [ -z "$validate_var" ]; then
        if [ -z "$(command -v nvim)" ]; then
            VIM_PROGRAM="nvim"
        else
            VIM_PROGRAM="vim"
        fi
    fi
fi

# echo "$#"
# for _ext in "$@"; do
#     echo "$_ext"
# done
# exit 0


TMUX_COMMAND=( tmux )
TMUX_COMMAND_STR="tmux"
if [ -z "$TMUX" ]; then
    # if [ -n "$SSH_CONNECTION" ] || [ -n "$SSH_CLIENT" ]; then
    #     if [ -z "$LC_TMUX" ]; then
    #         exec $VIM_PROGRAM "$@"
    #         exit 0
    #     elif [ -z "$LC_TMUX_SOCKET" ]; then
    #         exec $VIM_PROGRAM "$@"
    #         exit 0
    #     fi

    #     TMUX_COMMAND=( tmux -S "${LC_TMUX_SOCKET}" )
    #     TMUX_COMMAND_STR="tmux -S '${LC_TMUX_SOCKET}'"
    # else
        # exec $VIM_PROGRAM "$@"
        exec $VIM_PROGRAM --cmd 'cd $PWD' "$@"
        exit 0
    # fi
fi

NO_WAIT=0
if [ $# -ge 1 ]; then
    if [ "$1" = "--nowait" ]; then
        NO_WAIT=1
        shift
        # if [ "$1" = "sv" ]; then
        #     shift
        #     # 새 값 + 나머지 인자로 재설정
        #     set -- "$@" "/tmp/translate_byai.md"
        #     if [ ! -f "/tmp/translate_byai.md" ]; then
        #         echo "no file /tmp/translate_byai.md"
        #         exit 1
        #     fi
        # fi

        for arg in "$@"; do
            if [ "$arg" = "sv" ]; then
                # 새 값 + 나머지 인자로 재설정
                if [ ! -f "/tmp/translate_byai.md" ]; then
                    echo "no file /tmp/translate_byai.md"
                    exit 1
                fi
                shift
                set -- "$@" "/tmp/translate_byai.md"
                break
            fi
        done
    fi
fi

# echo "$@" > $HOME/test-cldarg.txt
signal="$VIM_PROGRAM-done-$$"
CURRENT_LINES=$(${TMUX_COMMAND[@]} display-message -p '#{pane_height}')

# vertical
# tmux split-window -h "vim '$@'; tmux wait-for -S $signal" \; wait-for $signal


if [ $NO_WAIT -ne 1 ]; then
    ${TMUX_COMMAND[@]} copy-mode
fi

tmp_editor_var=0
if [[ "$CLAUDECODE" = "1" ]] || [[ "$(${TMUX_COMMAND[@]} show-option -pqv @is_claude_code 2>/dev/null)" = "1" ]]; then
    tmp_editor_var=1
else
    tmp_editor_var=2
fi


# echo "vim enter" >> /tmp/test.txt
# horizontal
# $@를 직접 사용하면 tmux split-window에서 제대로 전달이 안되는 문제가 있어서 변수로 저장
TMUX_CMD="${TMUX_COMMAND_STR} set -p -t \$TMUX_PANE @aiagent_tmp_editor_localvar 1; export AIAGENT_TMP_EDITOR=${tmp_editor_var}; $VIM_PROGRAM --cmd 'cd $PWD' $@"
TMUX_CMD_WAIT="${TMUX_COMMAND_STR} set -p -t \$TMUX_PANE @aiagent_tmp_editor_localvar 1; export AIAGENT_TMP_EDITOR=${tmp_editor_var}; $VIM_PROGRAM --cmd 'cd $PWD' -c '\$' +startinsert! $@; VIMRC=\$?; ${TMUX_COMMAND_STR} set-environment CODEVIM_EXIT_$$ \$VIMRC; [ \$VIMRC -eq 10 ] && ${TMUX_COMMAND_STR} set-hook -w pane-exited 'run-shell \"$HOME/.dotfiles/.bin/codevim-autosend 1 && ${TMUX_COMMAND_STR} set-hook -uw pane-exited\"'"
if [ $CURRENT_LINES -ge 26 ]; then
    if [ $NO_WAIT -eq 1 ]; then
        ${TMUX_COMMAND[@]} split-window -v -l 13 "$TMUX_CMD"
    else
        ${TMUX_COMMAND[@]} split-window -v -l 13 "$TMUX_CMD_WAIT; ${TMUX_COMMAND_STR} wait-for -S $signal"
    fi
elif [ $CURRENT_LINES -ge 15 ]; then
    if [ $NO_WAIT -eq 1 ]; then
        ${TMUX_COMMAND[@]} split-window -v -l 7 "$TMUX_CMD"
    else
        ${TMUX_COMMAND[@]} split-window -v -l 7 "$TMUX_CMD_WAIT; ${TMUX_COMMAND_STR} wait-for -S $signal"
    fi
else
    if [ $NO_WAIT -eq 1 ]; then
        ${TMUX_COMMAND[@]} split-window -v "$TMUX_CMD"
    else
        ${TMUX_COMMAND[@]} split-window -v "$TMUX_CMD_WAIT; ${TMUX_COMMAND_STR} wait-for -S $signal"
    fi
fi

if [ $NO_WAIT -ne 1 ]; then
    ${TMUX_COMMAND[@]} last-pane
    ${TMUX_COMMAND[@]} send-keys -X scroll-up
    ${TMUX_COMMAND[@]} send-keys -X scroll-up
    ${TMUX_COMMAND[@]} send-keys -X scroll-up
    ${TMUX_COMMAND[@]} send-keys -X scroll-up
    ${TMUX_COMMAND[@]} last-pane
    ${TMUX_COMMAND[@]} wait-for $signal
    ${TMUX_COMMAND[@]} send-keys -X cancel
    VIM_EXIT=$(${TMUX_COMMAND[@]} show-environment CODEVIM_EXIT_$$ 2>/dev/null | cut -d= -f2)
    ${TMUX_COMMAND[@]} set-environment -u CODEVIM_EXIT_$$ 2>/dev/null
fi

unset AIAGENT_TMP_EDITOR
VIM_EXIT=${VIM_EXIT:--1}
# echo "vim quit (exit: $VIM_EXIT)" >> /tmp/test.txt

# if [ "$VIM_EXIT" -eq 10 ]; then
#     (sleep 0.15 && tmux send-keys -t 1 Enter) &
#     disown
# fi

# tmux new-window -n "claude-code-tmp-editor-$$" "$VIM_PROGRAM '$@'; tmux wait-for -S $signal" \; wait-for $signal

# rm -f $HOME/test-cldarg.txt

exit 0
