#!/bin/bash

# echo "VIM_PROG: $VIM_PROGRAM"
if [ -z "$VIM_PROGRAM" ]; then
	if [ -z "$(command -v nvim)" ]; then
		VIM_PROGRAM="nvim"
	else
		VIM_PROGRAM="vim"
	fi
else
	validate_var=$(command -v "$VIM_PROGRAM")
	if [ -z "$validate_var" ]; then
		if [ -z "$(command -v nvim)" ]; then
			VIM_PROGRAM="nvim"
		else
			VIM_PROGRAM="vim"
		fi
	fi
fi

# echo "$#"
# for _ext in "$@"; do
# 	echo "$_ext"
# done
# exit 0

if [ -z "$TMUX" ]; then
	exec $VIM_PROGRAM "$@"
fi

NO_WAIT=0
if [ $# -ge 1 ]; then
	if [ "$1" = "--nowait" ]; then
		NO_WAIT=1
		shift
		# if [ "$1" = "sv" ]; then
		# 	shift
		# 	# 새 값 + 나머지 인자로 재설정
		# 	set -- "$@" "/tmp/translate_byai.md"
		# 	if [ ! -f "/tmp/translate_byai.md" ]; then
		# 		echo "no file /tmp/translate_byai.md"
		# 		exit 1
		# 	fi
		# fi

		for arg in "$@"; do
			if [ "$arg" = "sv" ]; then
				# 새 값 + 나머지 인자로 재설정
				if [ ! -f "/tmp/translate_byai.md" ]; then
					echo "no file /tmp/translate_byai.md"
					exit 1
				fi
				shift
				set -- "$@" "/tmp/translate_byai.md"
				break
			fi
		done
	fi
fi

# echo "$@" > $HOME/test-cldarg.txt
signal="$VIM_PROGRAM-done-$$"
CURRENT_LINES=$(tmux display-message -p '#{pane_height}')

# vertical
# tmux split-window -h "vim '$@'; tmux wait-for -S $signal" \; wait-for $signal


if [ $NO_WAIT -ne 1 ]; then
	tmux copy-mode
fi

# horizontal
# $@를 직접 사용하면 tmux split-window에서 제대로 전달이 안되는 문제가 있어서 변수로 저장
TMUX_CMD="$VIM_PROGRAM --cmd 'cd $PWD' $@"
TMUX_CMD_WAIT="$VIM_PROGRAM --cmd 'cd $PWD' -c '\$' +startinsert! $@"
if [ $CURRENT_LINES -ge 26 ]; then
	if [ $NO_WAIT -eq 1 ]; then
		tmux split-window -v -l 13 "$TMUX_CMD"
	else
		tmux split-window -v -l 13 "$TMUX_CMD_WAIT; tmux wait-for -S $signal"
	fi
elif [ $CURRENT_LINES -ge 15 ]; then
	if [ $NO_WAIT -eq 1 ]; then
		tmux split-window -v -l 7 "$TMUX_CMD"
	else
		tmux split-window -v -l 7 "$TMUX_CMD_WAIT; tmux wait-for -S $signal"
	fi
else
	if [ $NO_WAIT -eq 1 ]; then
		tmux split-window -v "$TMUX_CMD"
	else
		tmux split-window -v "$TMUX_CMD_WAIT; tmux wait-for -S $signal"
	fi
fi

if [ $NO_WAIT -ne 1 ]; then
	tmux last-pane
	tmux send-keys -X scroll-up
	tmux send-keys -X scroll-up
	tmux send-keys -X scroll-up
	tmux send-keys -X scroll-up
	tmux last-pane
	tmux wait-for $signal
	tmux send-keys -X cancel
fi

# tmux new-window -n "claude-code-tmp-editor-$$" "$VIM_PROGRAM '$@'; tmux wait-for -S $signal" \; wait-for $signal

# rm -f $HOME/test-cldarg.txt

exit 0
