#!/bin/bash

function custom_vi() {
    clear
    echo "Do you want to open file with vi?"
    ls -alhF "$@" | awk '{
        for(i=9;i<=NF;i++) printf "%s ", $i;
        print ""
    }'
    read -sn 1 key
    if [[ -z "$key" ]] || [[ "$key" == $'\n' ]] || [[ "$key" == $'\r' ]]; then
        vi "$@"
    fi
}


if [ "$(locale -a 2>/dev/null | grep 'ko_KR.UTF-8')" ]; then
    export LANG=ko_KR.UTF-8
    export LC_ALL=ko_KR.UTF-8
elif [ "$(locale -a 2>/dev/null | grep 'ko_KR.utf8')" ]; then
    export LANG=ko_KR.UTF-8
    export LC_ALL=ko_KR.utf8
fi

PATH_BACKUP="$PATH"
export PATH=$( echo "$PATH" | sed -e "s|$HOME/\.dotfiles/\.bin:\?||" )

if [[ "$(uname -s)" = "Darwin" ]]; then

    if [ -n "$GIT_ASKPASS" ]; then
        if  grep -q "Code\.app" <<< "$GIT_ASKPASS"; then
            "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" "$@"
            exit 0
        elif  grep -q "Cursor\.app" <<< "$GIT_ASKPASS"; then
            "/Applications/Cursor.app/Contents/Resources/app/bin/code" "$@"
            exit 0
        elif  grep -q "\.vscode-server" <<< "$GIT_ASKPASS"; then
            "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" "$@"
            exit 0
        elif  grep -q "\.cursor-server" <<< "$GIT_ASKPASS"; then
            "/Applications/Cursor.app/Contents/Resources/app/bin/code" "$@"
            exit 0
        fi
    fi

    if [ -d "/Applications/Visual Studio Code.app" ]; then
        "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" "$@"
    elif [ -d "/Applications/Cursor.app" ]; then
        "/Applications/Cursor.app/Contents/Resources/app/bin/code" "$@"
    else
        vim "$@"
    fi

else
    if [ -n "$GIT_ASKPASS" ]; then
        if  grep -q "\.vscode-server" <<< "$GIT_ASKPASS"; then
            code "$@"
            exit 0
        elif  grep -q "\.cursor-server" <<< "$GIT_ASKPASS"; then
            cursor "$@"
            exit 0
        elif  grep -q "Code\.app" <<< "$GIT_ASKPASS"; then
            code "$@"
            exit 0
        elif  grep -q "Cursor\.app" <<< "$GIT_ASKPASS"; then
            cursor "$@"
            exit 0
        fi
    fi

    if [ -n "$(command -v cursor)" ]; then
        cursor "$@"
    elif [ -n "$(command -v code)" ]; then
        code "$@"
    else
        # vim "$@"
        custom_vi "$@"
    fi
fi


