#!/bin/bash

# 0 - VSCode
# 1 - Cursor
# 2 - AntiGravity
EDITOR_PRIORITY=0

IS_DARWIN=0
VSCODE_LOCAL_PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
CURSOR_LOCAL_PATH="/Applications/Cursor.app/Contents/Resources/app/bin/cursor"
ANTIGRAVITY_LOCAL_PATH="/Applications/Antigravity.app/Contents/Resources/app/bin/antigravity"

function custom_vi() {
    clear
    echo "Do you want to open file with vi?"
    ls -alhF "$@" | awk '{
        for(i=9;i<=NF;i++) printf "%s ", $i;
        print ""
    }'
    read -sn 1 key
    if [[ -z "$key" ]] || [[ "$key" == $'\n' ]] || [[ "$key" == $'\r' ]]; then
        vi "$@"
    fi
}


if [ "$(locale -a 2>/dev/null | grep 'ko_KR.UTF-8')" ]; then
    export LANG=ko_KR.UTF-8
    export LC_ALL=ko_KR.UTF-8
elif [ "$(locale -a 2>/dev/null | grep 'ko_KR.utf8')" ]; then
    export LANG=ko_KR.UTF-8
    export LC_ALL=ko_KR.utf8
fi

PATH_BACKUP="$PATH"
export PATH=$( echo "$PATH" | sed -e "s|$HOME/\.dotfiles/\.bin:\?||" )

function all_chcker() {

    if [ -n "$GIT_ASKPASS" ]; then

        if grep -q "Code\.app" <<< "$GIT_ASKPASS"; then
            "$VSCODE_LOCAL_PATH" "$@"
            exit 0
        elif grep -q "\.vscode-server" <<< "$GIT_ASKPASS"; then
            "$VSCODE_LOCAL_PATH" "$@"
            exit 0
        elif grep -q "Cursor\.app" <<< "$GIT_ASKPASS"; then
            "$CURSOR_LOCAL_PATH" "$@"
            exit 0
        elif grep -q "\.cursor-server" <<< "$GIT_ASKPASS"; then
            "$CURSOR_LOCAL_PATH" "$@"
            exit 0
        elif grep -q "Antigravity\.app" <<< "$GIT_ASKPASS"; then
            "$ANTIGRAVITY_LOCAL_PATH" "$@"
            exit 0
        elif grep -q "\.antigravity-server" <<< "$GIT_ASKPASS"; then
            "$ANTIGRAVITY_LOCAL_PATH" "$@"
            exit 0
        fi

        if [ $IS_DARWIN -eq 1 ]; then
            vim "$@"
        else
            custom_vi "$@"
        fi
        exit 0

    else

        if [ $EDITOR_PRIORITY -eq 0 ]; then
            if [ $IS_DARWIN -eq 1 ]; then
                if [ -f "$VSCODE_LOCAL_PATH" ]; then
                    "$VSCODE_LOCAL_PATH" "$@"
                    exit 0
                fi
            else
                local check_command=$(command -v "$VSCODE_LOCAL_PATH" 2>/dev/null)
                if [ -n "$check_command" ]; then
                    "$VSCODE_LOCAL_PATH" "$@"
                    exit 0
                fi
            fi
        elif [ $EDITOR_PRIORITY -eq 1 ]; then
            if [ $IS_DARWIN -eq 1 ]; then
                if [ -f "$CURSOR_LOCAL_PATH" ]; then
                    "$CURSOR_LOCAL_PATH" "$@"
                    exit 0
                elif [ -f "$VSCODE_LOCAL_PATH" ]; then
                    "$VSCODE_LOCAL_PATH" "$@"
                    exit 0
                fi
            else
                local check_command=$(command -v "$CURSOR_LOCAL_PATH" 2>/dev/null)
                if [ -n "$check_command" ]; then
                    "$CURSOR_LOCAL_PATH" "$@"
                    exit 0
                fi
                check_command=$(command -v "$VSCODE_LOCAL_PATH" 2>/dev/null)
                if [ -n "$check_command" ]; then
                    "$VSCODE_LOCAL_PATH" "$@"
                    exit 0
                fi
            fi
        elif [ $EDITOR_PRIORITY -eq 2 ]; then
            if [ $IS_DARWIN -eq 1 ]; then
                if [ -f "$ANTIGRAVITY_LOCAL_PATH" ]; then
                    "$ANTIGRAVITY_LOCAL_PATH" "$@"
                    exit 0
                elif [ -f "$VSCODE_LOCAL_PATH" ]; then
                    "$VSCODE_LOCAL_PATH" "$@"
                    exit 0
                fi
            else
                local check_command=$(command -v "$ANTIGRAVITY_LOCAL_PATH" 2>/dev/null)
                if [ -n "$check_command" ]; then
                    "$ANTIGRAVITY_LOCAL_PATH" "$@"
                    exit 0
                fi
                check_command=$(command -v "$VSCODE_LOCAL_PATH" 2>/dev/null)
                if [ -n "$check_command" ]; then
                    "$VSCODE_LOCAL_PATH" "$@"
                    exit 0
                fi
            fi
        else
            if [ $IS_DARWIN -eq 1 ]; then
                vim "$@"
            else
                custom_vi "$@"
            fi
            exit 0
        fi

    fi
}

EDITOR_FOUND_CHECK=0
if [[ "$(uname -s)" = "Darwin" ]]; then
    IS_DARWIN=1
    all_chcker $@
    exit 0
else
    IS_DARWIN=0
    VSCODE_LOCAL_PATH="code"
    CURSOR_LOCAL_PATH="cursor"
    ANTIGRAVITY_LOCAL_PATH="antigravity"

    all_chcker $@
    exit 0
fi


