#!/bin/bash

DEFAULT_EDITOR="vi"

if [ -z "$(command -v tmux)" ]; then
    echo "tmux command not found"
    exit 1
fi

if [ -z "$(command -v gemini)" ]; then
    echo "gemini is not installed"
    echo "https://geminicli.com/docs/get-started/installation/"
    echo "npm install -g @google/gemini-cli"
    exit 1
fi

if [ $# -eq 1 ]; then
    if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
        gemini --help
        exit 0
    elif [[ "$1" = "update" ]] || [[ "$1" = "--update" ]] || [[ "$1" = "upgrade" ]] || [[ "$1" = "--upgrade" ]]; then
        npm install -g @google/gemini-cli@latest
        if [ $? -ne 0 ]; then
            echo "update error"
            echo "rm -rf \"$(npm root -g)/@google/gemini-cli\""
            echo "rm -rf \"$(npm root -g)/@google/\".gemini-cli-*"
            echo "npm cache clean --force"
            echo "npm uninstall -g @google/gemini-cli"
            echo "npm install -g @google/gemini-cli"
        fi
        exit $?
    elif [[ "$1" = "-v" ]] || [[ "$1" = "-V" ]] || [[ "$1" = "version" ]] || [[ "$1" = "--version" ]]; then
		gemini --version
		exit $?
    elif [[ "$1" = "ls" ]] || [[ "$1" = "-ls" ]] || [[ "$1" = "--list-sessions" ]]; then
        gemini --list-sessions
        exit 0
    fi
fi

if [ $# -eq 2 ]; then
    if [ "$1" = "ds" ] || [ "$1" = "-ds" ] || [ "$1" = "--delete-session" ]; then
        gemini --delete-session $2
        gemini --list-sessions
        exit 0
    fi
fi

GLOBAL_OPTIONS=()
OPTS=()
MODEL_OPTS=()

MODEL_CONTINUE_FLAG=0
for arg in "$@"; do
    if [ $MODEL_CONTINUE_FLAG -eq 1 ]; then
        MODEL_OPTS+=("$arg")
        MODEL_CONTINUE_FLAG=0
        continue
    fi
    if [ "$arg" = "-c" ]; then
        GLOBAL_OPTIONS+=("-r")
    elif [ "$arg" = "-d" ] || [ "$arg" = "d" ] || [ "$arg" = "--dangerous" ] || [ "$arg" = "-y" ] || [ "$arg" = "--yolo" ]; then
        GLOBAL_OPTIONS+=("--yolo")
    elif [ "$arg" = "-a" ]|| [ "$arg" = "--all" ]; then
        GLOBAL_OPTIONS+=("--include-directories" "/")
    elif [ "$arg" = "-m" ] || [ "$arg" = "--model" ]; then
        MODEL_CONTINUE_FLAG=1
        MODEL_OPTS=("--model")
        continue
    elif [ "$arg" = "p" ] || [ "$arg" = "pro" ]; then
        if [ ${#MODEL_OPTS[@]} -le 0 ]; then
            MODEL_OPTS+=("--model" "pro")
        fi
    elif [ "$arg" = "f" ]; then
        if [ ${#MODEL_OPTS[@]} -le 0 ]; then
            MODEL_OPTS+=("--model" "flash")
        fi
    elif [ "$arg" = "fl" ]; then
        if [ ${#MODEL_OPTS[@]} -le 0 ]; then
            MODEL_OPTS+=("--model" "flash-lite")
        fi
    elif [ "$arg" = "a" ] || [ "$arg" = "auto" ]; then
        if [ ${#MODEL_OPTS[@]} -le 0 ]; then
            MODEL_OPTS+=("--model" "auto")
        fi
    elif [[ "$arg" = "vs" ]] || [[ "$arg" = "-vs" ]] || [[ "$arg" = "code" ]] || [[ "$arg" = "-code" ]]; then
            export EDITOR="code"
    elif [[ "$arg" = "vi" ]] || [[ "$arg" = "-vi" ]]; then
            if [ -n "$(command -v nvim)" ]; then
                export EDITOR="nvim"
            else
                export EDITOR="vim"
            fi
    elif [[ "$arg" = "vim" ]] || [[ "$arg" = "-vim" ]]; then
            export EDITOR="vim"
    elif [[ "$arg" = "nvi" ]] || [[ "$arg" = "-nvi" ]] || [[ "$arg" = "nvim" ]] || [[ "$arg" = "-nvim" ]]; then
            export EDITOR="nvim"
    else
        OPTS+=("$arg")
    fi
done

# default model
if [ ${#MODEL_OPTS[@]} -le 0 ]; then
    MODEL_OPTS+=("--model" "pro")
fi


if [ -z "$EDITOR" ]; then
    if [[ "$DEFAULT_EDITOR" = "code" ]]; then
        export EDITOR="code"
    elif [[ "$DEFAULT_EDITOR" = "vi" ]]; then
        if [ -n "$(command -v nvim)" ]; then
            export EDITOR="nvim"
        else
            export EDITOR="vim"
        fi
    else
        if [ -n "$GIT_ASKPASS" ]; then
            export EDITOR="code"
        elif [ -n "$(command -v nvim)" ]; then
            export EDITOR="nvim"
        else
            export EDITOR="vim"
        fi
    fi
fi

if [[ "$EDITOR" = "nvim" ]]; then
    export EDITOR="codenvim"
elif [[ "$EDITOR" = "vim" ]]; then
    export EDITOR="codevim"
fi


# 고유한 세션 이름 생성 (타임스탬프 + 프로세스 ID)
SESSION_NAME="gemini_$(date +%s)_$$"
TMUX_CONF="$HOME/.dotfiles/tmux/tmux.gemini.conf"

exec tmux -L sock_${SESSION_NAME} -f "$TMUX_CONF" \
    new-session -s "$SESSION_NAME" "sleep 0.1 && clear && gemini ${MODEL_OPTS[@]} ${GLOBAL_OPTIONS[@]} ${OPTS[@]} && tmux kill-session -t $SESSION_NAME"

# if [ -n "$VSCODE_INJECTION" ] || [ "$TERM_PROGRAM" = "vscode" ]; then
#     exec tmux new-session -s "$SESSION_NAME" "sleep 0.1 && clear && claude; tmux kill-session -t $SESSION_NAME"
# else
#     exec tmux new-session -s "$SESSION_NAME" "claude; tmux kill-session -t $SESSION_NAME"
# fi

