#!/bin/bash

DEFAULT_EDITOR="vi"
NVIM_IDE=0

if [ -z "$(command -v tmux)" ]; then
    echo "tmux command not found"
    exit 1
fi

if [ -z "$(command -v gemini)" ]; then
    echo "gemini is not installed"
    echo "https://geminicli.com/docs/get-started/installation/"
    echo "npm install -g @google/gemini-cli"
    exit 1
fi

if [ $# -eq 1 ]; then
    if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
        gemini --help
        exit $?
    elif [[ "$1" = "update" ]] || [[ "$1" = "--update" ]] || [[ "$1" = "upgrade" ]] || [[ "$1" = "--upgrade" ]]; then
        npm install -g @google/gemini-cli@latest
        if [ $? -ne 0 ]; then
            echo "update error"
            echo "rm -rf \"$(npm root -g)/@google/gemini-cli\""
            echo "rm -rf \"$(npm root -g)/@google/\".gemini-cli-*"
            echo "npm cache clean --force"
            echo "npm uninstall -g @google/gemini-cli"
            echo "npm install -g @google/gemini-cli"
        fi
        exit $?
    elif [[ "$1" = "-v" ]] || [[ "$1" = "-V" ]] || [[ "$1" = "version" ]] || [[ "$1" = "--version" ]]; then
        gemini --version
        exit $?
    elif [[ "$1" = "changelog" ]] || [[ "$1" = "ch" ]] || [[ "$1" = "-ch" ]] || [[ "$1" = "--changelog" ]]; then
        echo "release note: https://geminicli.com/docs/changelogs/latest/"
		echo "changelog   : https://geminicli.com/docs/changelogs/"
        echo "github  link: https://github.com/google-gemini/gemini-cli/releases"
        exit 0
    elif [[ "$1" = "ls" ]] || [[ "$1" = "-ls" ]] || [[ "$1" = "--list-sessions" ]]; then
        gemini --list-sessions
        exit 0
    fi
fi

if [ $# -eq 2 ]; then
    if [ "$1" = "ds" ] || [ "$1" = "-ds" ] || [ "$1" = "--delete-session" ]; then
        gemini --delete-session $2
        gemini --list-sessions
        exit 0
    fi
fi

for arg in "$@"; do
    if [[ "$arg" = "vs" ]] || [[ "$arg" = "-vs" ]] || [[ "$arg" = "code" ]] || [[ "$arg" = "-code" ]]; then
        export EDITOR="code"
        shift
    elif [[ "$arg" = "vi" ]] || [[ "$arg" = "-vi" ]]; then
        if [ -n "$(command -v nvim)" ]; then
            export EDITOR="nvim"
        else
            export EDITOR="vim"
        fi
        NVIM_IDE=1
        shift
    elif [[ "$arg" = "vim" ]] || [[ "$arg" = "-vim" ]]; then
        export EDITOR="vim"
		shift
        NVIM_IDE=1
    elif [[ "$arg" = "nvi" ]] || [[ "$arg" = "-nvi" ]] || [[ "$arg" = "nvim" ]] || [[ "$arg" = "-nvim" ]]; then
        export EDITOR="nvim"
        NVIM_IDE=1
        shift
    fi
done

if [ -z "$EDITOR" ]; then
    if [[ "$DEFAULT_EDITOR" = "code" ]]; then
        export EDITOR="code"
    elif [[ "$DEFAULT_EDITOR" = "vi" ]]; then
        if [ -n "$(command -v nvim)" ]; then
            export EDITOR="nvim"
        else
            export EDITOR="vim"
        fi
    else
        if [ -n "$GIT_ASKPASS" ]; then
            export EDITOR="code"
        elif [ -n "$(command -v nvim)" ]; then
            export EDITOR="nvim"
        else
            export EDITOR="vim"
        fi
    fi
fi

if [[ "$EDITOR" = "nvim" ]]; then
    export EDITOR="codenvim"
elif [[ "$EDITOR" = "vim" ]]; then
    export EDITOR="codevim"
fi


# export HTTP_PROXY=http://localhost:8080
# export HTTPS_PROXY=http://localhost:8080 
# export NODE_EXTRA_CA_CERTS=~/.mitmproxy/mitmproxy-ca-cert.pem
# export NODE_OPTIONS="--tls-keylog=$HOME/sslkeylog.log"

# sudo security add-trusted-cert -d -r trustRoot \
#     -k /Library/Keychains/System.keychain \
#     "$HOME/.mitmproxy/mitmproxy-ca-cert.pem"



# 고유한 세션 이름 생성 (타임스탬프 + 프로세스 ID)
SESSION_NAME="gemini_$(date +%s)_$$"
TMUX_CONF="$HOME/.dotfiles/tmux/tmux.gemini.conf"

# exec tmux -L sock_${SESSION_NAME} -f "$TMUX_CONF" \
#     new-session -s "$SESSION_NAME" "sleep 0.1 && clear && gemini ${MODEL_OPTS[@]} ${GLOBAL_OPTIONS[@]} ${OPTS[@]} && tmux kill-session -t $SESSION_NAME"

# if [ -n "$VSCODE_INJECTION" ] || [ "$TERM_PROGRAM" = "vscode" ]; then
#     exec tmux new-session -s "$SESSION_NAME" "sleep 0.1 && clear && claude; tmux kill-session -t $SESSION_NAME"
# else
#     exec tmux new-session -s "$SESSION_NAME" "claude; tmux kill-session -t $SESSION_NAME"
# fi



if [ -n "$TMUX" ]; then
    export EDITOR="$EDITOR";
    gld $@
    exit 0
elif [ "$NVIM_IDE" -eq 1 ]; then
    # vi 모드: window 2개 생성 (window 2: nvim 먼저, window 1: cld 나중)
    exec tmux -L sock_${SESSION_NAME} -f "$TMUX_CONF" \
        new-session -s "$SESSION_NAME" -d \; \
        new-window -t "$SESSION_NAME" "export TMUX_CLAUDECODE_IDE_NVIM=1; nvim" \; \
        send-keys -t "$SESSION_NAME:1" "export TMUX_CLAUDECODE_IDE_NVIM=1; export EDITOR=\"$EDITOR\"; sleep 0.1 && clear && gld $@; tmux kill-session -t $SESSION_NAME" C-m \; \
        select-window -t "$SESSION_NAME:1" \; \
        attach-session -t "$SESSION_NAME"
else
    exec tmux -L sock_${SESSION_NAME} -f "$TMUX_CONF" \
        new-session -s "$SESSION_NAME" "export EDITOR=\"$EDITOR\"; sleep 0.1 && clear && gld $@; tmux kill-session -t $SESSION_NAME"
    exec tmux -L sock_${SESSION_NAME} -f "$TMUX_CONF" \
        new-session -s "$SESSION_NAME" "sleep 0.1 && clear && gld $@ && tmux kill-session -t $SESSION_NAME"
fi



