#!/bin/bash
#!/usr/bin/zsh

R_MACRO="rloc"
R_CONFIG="$HOME/.ssh/config"

# <username> 설정 시 config 파일의 rloc username으로 바뀜
R_DEFAULT_DOWNLOAD_PATH="/Users/<username>/Down"

if [ $# -le 0 ]; then
    echo "Wrong Argument"
    exit 1
fi

# MacOS Test
R_PATH=""

FILES=()
FILE_PATH_STAT=0
R_SSH_KEY_PATH=""
R_USER=""

for arg in "$@"; do
    if [[ "$arg" = "--" ]]; then
        FILE_PATH_STAT=1
        continue
    fi
    if [ $FILE_PATH_STAT -eq 1 ]; then
        R_PATH="$arg"
        break
    fi

    FILES+=( "$arg" )
done


if [ -z "$R_PATH" ]; then
    CONFIG_READ=$(cat "$R_CONFIG" | grep -A 5 "Host.*${R_MACRO}$" )
    R_USER=$(echo "$CONFIG_READ" | grep "User" | awk -F ' ' '{ print $NF }')
    R_SSH_KEY_PATH=$(echo "$CONFIG_READ" | grep "IdentityFile" | awk -F ' ' '{ print $NF }')

    if [[ "${R_SSH_KEY_PATH:0:1}" = "~" ]]; then
        R_SSH_KEY_PATH=$( echo "${R_SSH_KEY_PATH}" | sed -e "s|^\~|$HOME|" )
    fi
    if [ -z "$R_USER" ]; then
        echo "No User, Edit ssh config"
        exit 1
    fi
    R_PATH=$(echo "${R_DEFAULT_DOWNLOAD_PATH}" | sed "s/<username>/${R_USER}/")
    # R_PATH="/Users/$R_USER/Downloads"
    echo "R_PATH: $R_PATH"
    ssh -F "$R_CONFIG" -i "$R_SSH_KEY_PATH" "$R_MACRO" "test ! -e '$R_PATH' && mkdir -p '$R_PATH'"
fi

if [ -z "$R_SSH_KEY_PATH" ]; then
    R_SSH_KEY_PATH="$HOME/.ssh/id_rsa"
fi

REMOTE_ADDR=$(echo "$SSH_CONNECTION" | awk -F ' ' '{ print $1 }')
echo ""
echo "Remote Address: $REMOTE_ADDR"

# source $HOME/.dotfiles/script/ssh-agent-init.sh
# source $HOME/.dotfiles/script/pass-ssh-agent.sh > /dev/null

scp -F "$R_CONFIG" -i /home/iblea/.ssh/id_rsa "${FILES[@]}" "$R_MACRO":"$R_PATH"
echo ""


if [ $? -ne 0 ]; then
    echo "Transfer Failed"
    echo ""
    exit 1
fi

echo "Download Path : ${R_PATH}"
echo "${REMOTE_ADDR}, transfered done"
echo ""
