#!/bin/bash

R_MACRO="rloc"
R_CONFIG="$HOME/.ssh/config"

# <username> 설정 시 config 파일의 rloc username으로 바뀜
R_DEFAULT_DOWNLOAD_PATH="./"

if [ $# -le 0 ]; then
    echo "Wrong Argument"
    exit 1
fi

# MacOS Test
R_PATH=""

FILES=()
FILE_PATH_STAT=0
R_SSH_KEY_PATH=""
R_USER=""

for arg in "$@"; do
    if [[ "$arg" = "--" ]]; then
        FILE_PATH_STAT=1
        continue
    fi
    if [ $FILE_PATH_STAT -eq 1 ]; then
        R_PATH="$arg"
        break
    fi

    FILES+=( "rloc:${arg}" )
done


if [ -z "$R_PATH" ]; then
    CONFIG_READ=$(cat "$R_CONFIG" | grep -A 5 "Host.*${R_MACRO}$" )
    R_USER=$(echo "$CONFIG_READ" | grep "User" | awk -F ' ' '{ print $NF }')
    R_SSH_KEY_PATH=$(echo "$CONFIG_READ" | grep "IdentityFile" | awk -F ' ' '{ print $NF }')

    if [[ "${R_SSH_KEY_PATH:0:1}" = "~" ]]; then
        R_SSH_KEY_PATH=$( echo "${R_SSH_KEY_PATH}" | sed -e "s|^\~|$HOME|" )
    fi
    if [ -z "$R_USER" ]; then
        echo "No User, Edit ssh config"
        exit 1
    fi
    R_PATH=$(echo "${R_DEFAULT_DOWNLOAD_PATH}" | sed "s/<username>/${R_USER}/")
    # R_PATH="/Users/$R_USER/Downloads"
fi

if [ -z "$R_SSH_KEY_PATH" ]; then
    R_SSH_KEY_PATH="$HOME/.ssh/id_rsa"
fi

REMOTE_ADDR=$(echo "$SSH_CONNECTION" | awk -F ' ' '{ print $1 }')
echo ""
echo "Remote Address: $REMOTE_ADDR"
if [ -z "$SSH_AUTH_SOCK" ]; then
    export SSH_AUTH_SOCK="$HOME/.ssh/ssh-agent.sock"
fi
ssh_agent_proc=$(ps -aef | grep ssh-agent | grep -F "$SSH_AUTH_SOCK" | grep -v "grep")
if [ -z "$ssh_agent_proc" ]; then
    eval $(ssh-agent -s -a "${SSH_AUTH_SOCK}") > /dev/null
fi
if [ -f "$HOME/.ssh/.passfile" ]; then
    ( { sleep .1; cat $HOME/.ssh/.passfile; } | script -q /dev/null -c "ssh-add $R_SSH_KEY_PATH" ) > /dev/null
else
    ssh-add "$R_SSH_KEY_PATH"
fi
echo ""


scp -F "$R_CONFIG" "${FILES[@]}" "$R_PATH"

if [ $? -ne 0 ]; then
    echo ""
    echo "Transfer Failed"
    echo ""
    exit 1
fi

echo ""
echo "Download Path : ${R_PATH}"
echo "${REMOTE_ADDR}, transfered done"
echo ""
