#!/bin/bash

R_MACRO="rloc"
R_CONFIG="$HOME/.ssh/config"

# <username> 설정 시 config 파일의 rloc username으로 바뀜
R_DEFAULT_DOWNLOAD_PATH="./"

if [ $# -le 0 ]; then
    echo "Wrong Argument"
    exit 1
fi

# MacOS Test
R_PATH=""

FILES=()
FILE_PATH_STAT=0
R_SSH_KEY_PATH=""
R_USER=""
R_HOME=""

for arg in "$@"; do
    if [[ "$arg" = "--" ]]; then
        FILE_PATH_STAT=1
        continue
    fi
    if [ $FILE_PATH_STAT -eq 1 ]; then
        R_PATH="$arg"
        break
    fi

    if [[ "${arg:0:1}" = "~" ]]; then
        if [ -z "$R_HOME" ]; then
            R_HOME=$(ssh -F "$R_CONFIG" -i "$R_SSH_KEY_PATH" "$R_MACRO" "echo \$HOME")
        fi
        arg=$(echo "${arg}" | sed -e "s|^\~|$R_HOME|")
    fi
    FILES+=( "rloc:${arg}" )
done


if [ -z "$R_PATH" ]; then
    CONFIG_READ=$(cat "$R_CONFIG" | grep -A 5 "Host.*${R_MACRO}$" )
    R_USER=$(echo "$CONFIG_READ" | grep "User" | awk -F ' ' '{ print $NF }')
    R_SSH_KEY_PATH=$(echo "$CONFIG_READ" | grep "IdentityFile" | awk -F ' ' '{ print $NF }')

    if [[ "${R_SSH_KEY_PATH:0:1}" = "~" ]]; then
        R_SSH_KEY_PATH=$( echo "${R_SSH_KEY_PATH}" | sed -e "s|^\~|$HOME|" )
    fi
    if [ -z "$R_USER" ]; then
        echo "No User, Edit ssh config"
        exit 1
    fi
    R_PATH=$(echo "${R_DEFAULT_DOWNLOAD_PATH}" | sed "s/<username>/${R_USER}/")
    # R_PATH="/Users/$R_USER/Downloads"
fi

if [ -z "$R_SSH_KEY_PATH" ]; then
    R_SSH_KEY_PATH="$HOME/.ssh/id_rsa"
fi

REMOTE_ADDR=$(echo "$SSH_CONNECTION" | awk -F ' ' '{ print $1 }')
echo ""
echo "Remote Address: $REMOTE_ADDR"

source $HOME/.dotfiles/script/ssh-agent-init.sh
source $HOME/.dotfiles/script/passkey_filepath
if [ -f "$PASSPATH_SSH_AGENT" ]; then
    ( { sleep .1; echo "$(cat ""$PASSPATH_SSH_AGENT"" | tr -d '\r' | tr -d '\n')"; } | script -q /dev/null -c "ssh-add $HOME/.ssh/id_rsa" ) > /dev/null
else
    ssh-add "$R_SSH_KEY_PATH"
fi
echo ""


scp -r -F "$R_CONFIG" "${FILES[@]}" "$R_PATH"

if [ $? -ne 0 ]; then
    echo ""
    echo "Transfer Failed"
    echo ""
    exit 1
fi

echo ""
echo "Download Path : ${R_PATH}"
echo "${REMOTE_ADDR}, transfered done"
echo ""
