#!/bin/bash

MODEL_SELECT=""
if [ $# -eq 1 ]; then
    if [[ "$1" = "s" ]] || [[ "$1" = "o" ]]; then
        MODEL_SELECT="$1"
        shift
    elif [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
        opencode --help
        exit 0
    elif [[ "$1" = "-v" ]] || [[ "$1" = "--version" ]]; then
        opencode --version
        exit 0
    fi
else
    MODEL_SELECT="$1"
    shift
fi

if [[ "$1" = "update" ]] || [[ "$1" = "--update" ]] || [[ "$1" = "upgrade" ]] || [[ "$1" = "--upgrade" ]]; then
    opencode update
    exit 0
fi

if [[ "$MODEL_SELECT" = "s" ]] || [[ "$MODEL_SELECT" = "S" ]]; then
    # TERM=screen opencode --model "anthropic/claude-sonnet-4-5"
    opencode --model "anthropic/claude-sonnet-4-5" $@
elif [[ "$MODEL_SELECT" = "o" ]]  || [[ "$MODEL_SELECT" = "O" ]]; then
    # TERM=screen opencode --model "anthropic/claude-opus-4-5"
    opencode --model "anthropic/claude-opus-4-5" $@
else
    # TERM=screen opencode
    opencode $@
fi

