#!/bin/bash

MODEL_SELECT=""
if [ $# -eq 0 ]; then
    MODEL_SELECT="s"
elif [ $# -eq 1 ]; then
    if [ "$1" = "s" ] || [ "$1" = "o" ]; then
        MODEL_SELECT="$1"
        shift
    fi
else
    MODEL_SELECT="$1"
    shift
fi

if [ "$MODEL_SELECT" = "s" ] || [ "$MODEL_SELECT" = "S" ]; then
    TERM=screen opencode --model "anthropic/claude-sonnet-4-5"
elif [ "$MODEL_SELECT" = "o" ]  || [ "$MODEL_SELECT" = "O" ]; then
    TERM=screen opencode --model "anthropic/claude-opus-4-1"
else
    TERM=screen opencode
fi

