#!/bin/bash

VIM_PROGRAM=""

NVIM_PATH="nvim"
VIM_PATH="vim"

if [ -n "$(command -v $NVIM_PATH)" ]; then
    VIM_PROGRAM="n"
else
    VIM_PROGRAM="o"
fi

if [ $# -ge 1 ]; then
    if [ "$1" = "n" ] || [ "$1" = "N" ]; then
        VIM_PROGRAM="n"
        CLAUDE_OPT="s"
    elif [ "$1" = "o" ] || [ "$1" = "O" ]; then
        VIM_PROGRAM="o"
    fi
fi

# VIM_DEFAULT=$(vim --version | head -n 1 | awk '{ print $1 }')
# if [ "$VIM_DEFAULT" = "NVIM" ]; then
#     VIM_PROGRAM="n"
# else
#     VIM_PROGRAM="o"
# fi

if [ -n "$VIMTERM" ] && [ "$VIMTERM" -eq "1" ]; then
	echo "vim terminal already opened!"
	exit 0
fi


if [ "$VIM_PROGRAM" = "n" ]; then
    $NVIM_PATH -c "set nonu" \
        -c "set nornu | set mouse=a | set scrollback=10000 | set scrolloff=0" \
        -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
		-c "terminal VIMTERM=1 \"$(which zsh)\"" \
        -c "autocmd TermClose * quit!" \
        -c "startinsert"
else
    $VIM_PATH -c "set nonu" \
        -c "set nornu | set mouse=a | set termwinscroll=10000 | set scrolloff=0" \
        -c "execute 'tnoremap <c-h> <LEFT>' | execute 'tnoremap <c-j> <DOWN>' | execute 'tnoremap <c-k> <UP>' | execute 'tnoremap <c-l> <RIGHT>'" \
        -c "set shell=$(which zsh | sed 's/ /\\ /g')" \
		-c "let \$VIMTERM=1 | let \$SHELL=\"$(which zsh)\" | terminal ++close ++curwin"
fi

exit 0
