#!/bin/bash


curpwd=$(pwd)

if [[ "$curpwd" != "/" ]]; then
    curpwd="${curpwd}/"
fi

opts=( )
keyword="$@"
if [ $# -ge 2 ]; then
    IFS='' array=( $@ )
    IFS='' opts=( $(echo "${array[@]:0:${#array[@]}-1}") )
    keyword=${array[((${#array[@]}-1))]}
fi

# opts=( )
# keyword="$@"
# if [ $# -ge 2 ]; then
#     IFS='' array=( $@ )
#     IFS='' opts=( $(echo "${array[@]:0:${#array[@]}-1}") )
#     keyword=${array[((${#array[@]}-1))]}
# fi

opts=()
last_idx=$(($# ))
hyphen_hyphen=""
for i in $(seq 1 $last_idx); do
    if [ -n "${hyphen_hyphen}" ]; then
        keyword="${keyword}${!i}"
        continue
    fi
    if [ $i -eq $last_idx ]; then
        keyword="${!i}"
    else
        if [ "${!i}" = "--" ]; then
            echo ".."
            hyphen_hyphen="--"
        else
            opts+=("${!i}")
        fi
    fi
done



source $HOME/.dotfiles/grepscript/grep_exclude

# grep --color=always -rnIH ${search_str[@]} | sed -e "s|^|${curpwd}|1" -e "s/\:/\n/2" -e "s|\[m\[K\s*|[m[K|g"
# grep --color=always -rnIH ${search_str[@]} | sed -e "s|^|${curpwd}|1" -e "s/\:/\n/2"
grep --color=always -rnIH ${opts[@]} ${exclude_str[@]} ${hyphen_hyphen} "$keyword" | sed -e "s|^|${curpwd}|1" -e "s|\:\[m\[K\s*|[m[K\n|2"
