#!/bin/bash


curpwd=$(pwd)

if [[ "$curpwd" != "/" ]]; then
    curpwd="${curpwd}/"
fi

opts=( )
keyword="$@"
if [ $# -ge 2 ]; then
    IFS='' array=( $@ )
    IFS='' opts=( $(echo "${array[@]:0:${#array[@]}-1}") )
    keyword=${array[((${#array[@]}-1))]}
fi

source $HOME/.dotfiles/grepscript/grep_exclude

# -P option : perl regex
# grep --color=always -rnIHP ${search_str[@]} | sed -e "p" -e "s/:/ | /2" | sed -n "2~2p"
# grep --color=always -rnIHP ${search_str[@]} | sed -e "s/:/ | /2" -e "s|\[m\[K\s*|[m[K|g"
# grep --color=always -rnIHP ${search_str[@]} | sed -e "s/:/ | /2"
grep --color=always -rnIHP ${opts[@]} ${exclude_str[@]} "$keyword" | sed -e "s/\:\[m\[K\s*/ |[m[K /2"
echo "${exclude_str[@]}"
echo "${opts[@]}"
