#!/bin/bash


curpwd=$(pwd)

if [[ "$curpwd" != "/" ]]; then
    curpwd="${curpwd}/"
fi

# opts=( )
# keyword="$@"
# if [ $# -ge 2 ]; then
#     IFS='' array=( $@ )
#     IFS='' opts=( $(echo "${array[@]:0:${#array[@]}-1}") )
#     keyword=${array[((${#array[@]}-1))]}
# fi

opts=()
last_idx=$(($# ))
for i in $(seq 1 $last_idx); do
    if [ $i -eq $last_idx ]; then
        keyword="${!i}"
    else
        opts+=("${!i}")
    fi
done

source $HOME/.dotfiles/grepscript/grep_exclude

# -P option : perl regex
# grep --color=always -rnIHP ${search_str[@]} | sed -e "p" -e "s/:/ | /2" | sed -n "2~2p"
# grep --color=always -rnIHP ${search_str[@]} | sed -e "s/:/ | /2" -e "s|\[m\[K\s*|[m[K|g"
# grep --color=always -rnIHP ${search_str[@]} | sed -e "s/:/ | /2"
# grep --color=always -rnIHP ${exclude_str[@]} $@ | sed -e "s/\:\[m\[K\s*/ |[m[K /2"

grep --color=always -rnIHP ${opts[@]} ${exclude_str[@]} "$keyword" | sed -e "s/\:\[m\[K\s*/ |[m[K /2"

# grep --color=always -rnIHP ${exclude_str[@]} $@
# echo "${exclude_str[@]}"
# echo "${opts[@]}"
